steps:
  - name: node
    dir: "./apps/runner"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        npm install -g pnpm
        pnpm install
        pnpm build
  - name: "gcr.io/cloud-builders/docker"
    dir: "./apps/runner"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/common-os/runner:$SHORT_SHA",
        "-f",
        "Dockerfile",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    dir: "."
    args:
      [
        "tag",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/common-os/runner:$SHORT_SHA",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/common-os/runner:prod",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/common-os/runner",
        "--all-tags",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - common-os-runner-prod
      - --region=europe-west1
      - --platform=managed
      - --image=europe-west1-docker.pkg.dev/$PROJECT_ID/common-os/runner:prod
      - --no-cpu-throttling
      - --service-account=common-os-api@$PROJECT_ID.iam.gserviceaccount.com
    timeout: 1800s

options:
  logging: CLOUD_LOGGING_ONLY
